### ISSUE TITLE
Quotes should use extension nodes not delimiters

### ISSUE THREAD

**Issue by lpw25** [modlfo/pla#1]
Extension nodes should be of the form:

```
[%pla {| ... |}]
```

rather than:

```
{pla| ... |pla}
```

The delimiters in the syntax `{| ... |}` is not intended to indicate extensions. It is intended to allow quoting of any string without the use of escaping.

The current approach means it is not possible to include the string `|pla}` inside a template.

**Comment by modlfo** [comment]
I considered using extension nodes, but for aesthetic reasons I decided to go with `{pla| .. |pla}`. 

In order to solve the problem of not being able to use `|pla}` inside a template (which can be useful to create code with Pla templates) I thought about doing it as follows.

``` ocaml
let makePlaTemplate (text:string) : Pla.t =
   Pla.join  [Pla.string "{pla|"; Pla.string text; Pla.string "|pla}" ] ;;

let text = makePlaTemplate {| template text here |} ;;

```

It's not the nicest way, but I was hoping this not to be a frequent case.

**Comment by lpw25** [comment]
The aesthetics are less important than consistency. The point is a ppx should only be interpreting extension points and attributes, not arbitrary bits of the language. Half the point of the ppx/extension points work was to make all such extensions obvious in the source code. When a user sees`{pla| ... |pla}` they should be able to safely assume it is a normal string literal. When a user sees `[%pla ...]` they know this is something to be interpreted by a ppx.

**Comment by modlfo** [comment]
I agree that consistency is important but when writing/reading code aesthetics and simplicity matters. It would be nice having a short-cut syntax as in `let` bindings (I took this bit from your presentation):

``` ocaml
(* This syntax is harder to read and write *)
[%lwt let x = f () in
[%lwt let y = g () in
expr] ]

(* This one is more usable and less intrusive *)
let%lwt x = f () in
let%lwt y = g () in
expr
```

A short-cut syntax for `[%pla {| ... |}]` would be nice and I'll be happy to change the library. For example:

```
{%pla| ... |}
```

**Comment by lpw25** [comment]
Sure. Although it is worth pointing out the original motivation for `let%` was around the amount of nested `]` required which is not merely aesthetic but actually makes code more difficult to understand. In the case of `{| ... |}` there is only a change in the number of characters in the delimiters, so the need for a short-cut is less clear cut.

I've advocated for a shortcut syntax for `{%foo|` before, so I'm not completely against it. But I'd rather see libraries all consistently use `[%foo {| ... |}]` until such a thing exists.

**Comment by modlfo** [comment]
I have implemented support for `[%foo {| ... |}]` however `{pla| ... |pla}` is still supported. I have updated the documentation to prefer `[%foo {| ... |}]`.

I hope in the future having the shortcut syntax because the code looks quite cluttered for small templates.
